import 'package:cloud_firestore/cloud_firestore.dart';

/// AI-generated insights and recommendations
///
/// Per DATA_MODELS.md specification:
/// Generated by Analyst Agent to provide actionable financial insights.
/// Includes achievements, alerts, recommendations, trends, and anomalies.
///
/// Features:
/// - Priority-based ordering
/// - Optional time period context
/// - Actionable CTAs
/// - Auto-expiration
/// - v3: Tracks which AI agent generated the insight
class Insight {
  final String id;
  final String userId;
  final InsightType type;
  final InsightPriority priority;

  final String title;
  final String message;

  /// Additional data specific to insight type
  final Map<String, dynamic> data;

  /// Related category (optional)
  final String? category;

  /// Time period this insight covers (optional)
  final InsightPeriod? period;

  /// Call-to-action (optional)
  final InsightAction? action;

  final InsightStatus status;
  final DateTime generatedAt;

  /// NEW v3: Which AI agent generated this insight
  /// Typically: "analyst_agent", "financial_copilot", "vision"
  final String generatedBy;

  /// Optional expiration timestamp
  final DateTime? expiresAt;

  Insight({
    required this.id,
    required this.userId,
    required this.type,
    required this.priority,
    required this.title,
    required this.message,
    required this.data,
    this.category,
    this.period,
    this.action,
    required this.status,
    required this.generatedAt,
    required this.generatedBy,
    this.expiresAt,
  });

  /// Create from Firestore document
  factory Insight.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Insight(
      id: doc.id,
      userId: (data['user_id'] ?? data['userId']) as String,
      type: InsightType.values.byName(data['type'] as String),
      priority: InsightPriority.values.byName(data['priority'] as String),
      title: data['title'] as String,
      message: data['message'] as String,
      data: Map<String, dynamic>.from(data['data'] ?? {}),
      category: data['category'] as String?,
      period: data['period'] != null
          ? InsightPeriod.fromMap(data['period'] as Map<String, dynamic>)
          : null,
      action: data['action'] != null
          ? InsightAction.fromMap(data['action'] as Map<String, dynamic>)
          : null,
      status: InsightStatus.values.byName(data['status'] as String),
      generatedAt: (data['generatedAt'] as Timestamp).toDate(),
      generatedBy: data['generatedBy'] as String,
      expiresAt: data['expiresAt'] != null
          ? (data['expiresAt'] as Timestamp).toDate()
          : null,
    );
  }

  /// Convert to Firestore document
  Map<String, dynamic> toFirestore() {
    return {
      'user_id': userId,
      'type': type.name,
      'priority': priority.name,
      'title': title,
      'message': message,
      'data': data,
      'category': category,
      'period': period?.toMap(),
      'action': action?.toMap(),
      'status': status.name,
      'generatedAt': Timestamp.fromDate(generatedAt),
      'generatedBy': generatedBy,
      'expiresAt': expiresAt != null ? Timestamp.fromDate(expiresAt!) : null,
    };
  }

  /// Check if insight is expired
  bool get isExpired {
    if (expiresAt == null) return false;
    return DateTime.now().isAfter(expiresAt!);
  }

  /// Check if insight is active and not expired
  bool get isActive => status == InsightStatus.active && !isExpired;

  /// Copy with updated status
  Insight copyWith({
    InsightStatus? status,
  }) {
    return Insight(
      id: id,
      userId: userId,
      type: type,
      priority: priority,
      title: title,
      message: message,
      data: data,
      category: category,
      period: period,
      action: action,
      status: status ?? this.status,
      generatedAt: generatedAt,
      generatedBy: generatedBy,
      expiresAt: expiresAt,
    );
  }

  /// Dismiss this insight
  Insight dismiss() => copyWith(status: InsightStatus.dismissed);
}

/// Time period covered by insight
class InsightPeriod {
  final DateTime start;
  final DateTime end;

  InsightPeriod({
    required this.start,
    required this.end,
  });

  factory InsightPeriod.fromMap(Map<String, dynamic> map) {
    return InsightPeriod(
      start: (map['start'] as Timestamp).toDate(),
      end: (map['end'] as Timestamp).toDate(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'start': Timestamp.fromDate(start),
      'end': Timestamp.fromDate(end),
    };
  }

  /// Get period duration in days
  int get durationInDays => end.difference(start).inDays;
}

/// Call-to-action for insight
class InsightAction {
  final String label;
  final InsightActionType type;
  final String? target;

  InsightAction({
    required this.label,
    required this.type,
    this.target,
  });

  factory InsightAction.fromMap(Map<String, dynamic> map) {
    return InsightAction(
      label: map['label'] as String,
      type: InsightActionType.values.byName(map['type'] as String),
      target: map['target'] as String?,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'label': label,
      'type': type.name,
      'target': target,
    };
  }
}

/// Type of insight
enum InsightType {
  /// Positive achievement (e.g., "You saved $200 this month!")
  achievement,

  /// Warning or alert (e.g., "You're over budget on dining")
  alert,

  /// Actionable recommendation (e.g., "Try reducing coffee spending")
  recommendation,

  /// Pattern or trend observation (e.g., "Spending up 15% vs last month")
  trend,

  /// Unusual activity detected (e.g., "Large purchase detected")
  anomaly,
}

/// Priority level
enum InsightPriority {
  high,
  medium,
  low,
}

/// Insight status
enum InsightStatus {
  active,
  dismissed,
  expired,
}

/// Action type
enum InsightActionType {
  navigate,
  dismiss,
}
